name: emersonacademy
favicon: null
layout_spectrum: 0.52688
typography_spectrum: 0.38114717812277377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#aabcca'
    - '#f2ece0'
    - '#7b5f49'
    - '#8c181a'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
