name: emersonacademy
favicon: null
layout_spectrum: 0.51586
typography_spectrum: 0.38114717812277377
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030000'
    - '#f6f6f6'
    - '#473e00'
    - '#b3a197'
    - '#d65e2c'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
